language: python
python:
  - "2.7"
# Install dependencies
install:
    - "pip install -r project_template/requirements.txt"
    - "pip install coverage coveralls"

before_script:
  - psql -c "CREATE USER cowhite WITH PASSWORD 'cowhite' CREATEDB;" -U postgres

script: coverage run project_template/manage.py test accounts transactions

after_success: coveralls
